#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("xam.shineButton.Resource", IsApplication=false)]

namespace xam.shineButton
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int allow_random_color = 2130771974;
			
			// aapt resource value: 0x7f010008
			public static int big_shine_color = 2130771976;
			
			// aapt resource value: 0x7f010000
			public static int btn_color = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int btn_fill_color = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public static int click_animation_duration = 2130771978;
			
			// aapt resource value: 0x7f010005
			public static int enable_flashing = 2130771973;
			
			// aapt resource value: 0x7f010009
			public static int shine_animation_duration = 2130771977;
			
			// aapt resource value: 0x7f010002
			public static int shine_count = 2130771970;
			
			// aapt resource value: 0x7f01000b
			public static int shine_distance_multiple = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int shine_size = 2130771980;
			
			// aapt resource value: 0x7f010003
			public static int shine_turn_angle = 2130771971;
			
			// aapt resource value: 0x7f01000d
			public static int siShape = 2130771981;
			
			// aapt resource value: 0x7f010007
			public static int small_shine_color = 2130771975;
			
			// aapt resource value: 0x7f010004
			public static int small_shine_offset_angle = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f020000
			public static int heart = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int like = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int smile = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int star = 2130837507;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public static int app_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PorterImageView = new int[] {
					2130771981};
			
			// aapt resource value: 0
			public static int PorterImageView_siShape = 0;
			
			public static int[] ShineButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 6
			public static int ShineButton_allow_random_color = 6;
			
			// aapt resource value: 8
			public static int ShineButton_big_shine_color = 8;
			
			// aapt resource value: 0
			public static int ShineButton_btn_color = 0;
			
			// aapt resource value: 1
			public static int ShineButton_btn_fill_color = 1;
			
			// aapt resource value: 10
			public static int ShineButton_click_animation_duration = 10;
			
			// aapt resource value: 5
			public static int ShineButton_enable_flashing = 5;
			
			// aapt resource value: 9
			public static int ShineButton_shine_animation_duration = 9;
			
			// aapt resource value: 2
			public static int ShineButton_shine_count = 2;
			
			// aapt resource value: 11
			public static int ShineButton_shine_distance_multiple = 11;
			
			// aapt resource value: 12
			public static int ShineButton_shine_size = 12;
			
			// aapt resource value: 3
			public static int ShineButton_shine_turn_angle = 3;
			
			// aapt resource value: 7
			public static int ShineButton_small_shine_color = 7;
			
			// aapt resource value: 4
			public static int ShineButton_small_shine_offset_angle = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
